-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.app_settings (
  key text NOT NULL,
  value jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT app_settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.cart_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  session_id text,
  product_id uuid,
  option_combination_id uuid,
  selected_options jsonb,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_option_combination_id_fkey FOREIGN KEY (option_combination_id) REFERENCES public.product_option_combinations(id),
  CONSTRAINT cart_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.fixed_content (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  section_type text NOT NULL,
  title text,
  content text NOT NULL,
  is_active boolean DEFAULT true,
  sort_order integer,
  CONSTRAINT fixed_content_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inquiries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  session_id uuid NOT NULL,
  utm jsonb,
  source_channel text,
  inquiry_kind USER-DEFINED,
  priorities jsonb,
  items ARRAY,
  item_custom text,
  quantity integer,
  design USER-DEFINED,
  needed_date date,
  heard_about text,
  name text,
  contact text,
  preferred_time_start time without time zone,
  preferred_time_end time without time zone,
  last_step_completed integer DEFAULT 0,
  status USER-DEFINED DEFAULT 'new'::inquiry_status,
  assignee uuid,
  admin_notes text,
  privacy_consent boolean DEFAULT false,
  privacy_consent_at timestamp with time zone,
  source USER-DEFINED,
  CONSTRAINT inquiries_pkey PRIMARY KEY (id),
  CONSTRAINT inquiries_assignee_fkey FOREIGN KEY (assignee) REFERENCES public.profiles(id)
);
CREATE TABLE public.inquiry_events (
  id bigint NOT NULL DEFAULT nextval('inquiry_events_id_seq'::regclass),
  inquiry_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  actor uuid,
  type text NOT NULL,
  payload jsonb,
  CONSTRAINT inquiry_events_pkey PRIMARY KEY (id),
  CONSTRAINT inquiry_events_inquiry_id_fkey FOREIGN KEY (inquiry_id) REFERENCES public.inquiries(id),
  CONSTRAINT inquiry_events_actor_fkey FOREIGN KEY (actor) REFERENCES public.profiles(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  order_id uuid,
  product_id uuid,
  product_name text,
  product_slug text,
  selected_options jsonb,
  unit_price numeric NOT NULL,
  quantity integer NOT NULL,
  total_price numeric NOT NULL,
  attributes jsonb,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  session_id text,
  shop_order_no text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'pending'::text,
  subtotal numeric NOT NULL DEFAULT 0,
  shipping_fee numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  payment_method text,
  order_name text,
  order_phone text,
  order_email text,
  shipping_method text,
  same_as_orderer boolean DEFAULT true,
  receiver_name text,
  receiver_phone text,
  zip_code text,
  addr1 text,
  addr2 text,
  pg_provider text DEFAULT 'easypay'::text,
  pg_authorization_id text,
  pg_approval jsonb,
  pg_return_payload jsonb,
  cancel_reason text,
  refund_reason text,
  work_status text DEFAULT 'pending'::text,
  shipping_status text DEFAULT 'ready'::text,
  shipping_memo text,
  payment_status text DEFAULT 'paid'::text,
  attributes jsonb,
  cart_snapshot jsonb,
  refunded_amount numeric DEFAULT 0,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.portfolio (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  title text NOT NULL,
  description text,
  photo text,
  date date,
  image_url text,
  category text,
  sort_order integer,
  is_active boolean DEFAULT true,
  CONSTRAINT portfolio_pkey PRIMARY KEY (id)
);
CREATE TABLE public.product_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  parent_id uuid,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  image_url text,
  icon_url text,
  CONSTRAINT product_categories_pkey PRIMARY KEY (id),
  CONSTRAINT product_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.product_categories(id)
);
CREATE TABLE public.product_content (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  product_id uuid,
  section_type text NOT NULL,
  title text,
  content text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  CONSTRAINT product_content_pkey PRIMARY KEY (id),
  CONSTRAINT product_content_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  product_id uuid,
  url text NOT NULL,
  alt_text text,
  sort_order integer DEFAULT 0,
  is_primary boolean DEFAULT false,
  CONSTRAINT product_images_pkey PRIMARY KEY (id),
  CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_option_combinations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  product_id uuid,
  option_ids ARRAY NOT NULL,
  price numeric,
  sale_price numeric,
  stock_quantity integer DEFAULT 0,
  sku text UNIQUE,
  is_active boolean DEFAULT true,
  CONSTRAINT product_option_combinations_pkey PRIMARY KEY (id),
  CONSTRAINT product_option_combinations_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  product_id uuid,
  type text NOT NULL,
  name text NOT NULL,
  value text NOT NULL,
  price_modifier numeric DEFAULT 0,
  stock_quantity integer DEFAULT 0,
  sku_suffix text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  image_url text,
  color_hex text,
  CONSTRAINT product_options_pkey PRIMARY KEY (id),
  CONSTRAINT product_options_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  short_description text,
  sku text UNIQUE,
  category_id uuid,
  base_price numeric DEFAULT 0,
  sale_price numeric,
  cost_price numeric,
  manage_stock boolean DEFAULT true,
  stock_quantity integer DEFAULT 0,
  low_stock_threshold integer DEFAULT 5,
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  meta_title text,
  meta_description text,
  attributes jsonb DEFAULT '{}'::jsonb,
  sort_order integer DEFAULT 0,
  size_chart_url text,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.product_categories(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'agent'::user_role,
  display_name text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  author uuid,
  rating integer NOT NULL CHECK (rating >= 0 AND rating <= 5),
  title text NOT NULL,
  content text NOT NULL,
  images ARRAY,
  display_at timestamp with time zone NOT NULL DEFAULT now(),
  author_name text,
  view_count integer NOT NULL DEFAULT 0,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_author_fkey FOREIGN KEY (author) REFERENCES auth.users(id)
);
CREATE TABLE public.user_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  label text NOT NULL,
  orderer_name text,
  orderer_phone text,
  receiver_name text,
  receiver_phone text,
  zip_code text,
  addr1 text,
  addr2 text,
  is_default boolean DEFAULT false,
  CONSTRAINT user_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT user_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);